<?php
 
/**
 * For more informaiton about the different API controls available see:
 * http://api.drupal.org/api/drupal/developer--topics--forms_api_reference.html/6
 */
 
function analisa_menu() {
    $items['analisa'] = array(
        'title' => 'Analisa Belanja',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('analisa_form'),
        'access callback' => TRUE,
    );
    $items['analisabl'] = array(
        'title' => 'Rekap Belanja Langsung',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('analisabl_form'),
        'access callback' => TRUE,
    );	
    $items['analisabtl'] = array(
        'title' => 'Rekap Belanja Tidak Langsung',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('analisabtl_form'),
        'access callback' => TRUE,
    );	
    return $items;
}
 
/**
 * This is form containing every form element type available.
 */
function analisa_form() {
	drupal_add_css('files/css/kegiatancam.css');


	$output = genReportBelanjaSKPDX('2');
	$form['formdata']['submit'] = array (
		'#type' => 'submit',
		'#value' => 'Cetak'
	);
	$form['formdata']['submitexcel'] = array (
		'#type' => 'submit',
		'#value' => 'Excel',
	);
	$form['formdata']['value'] = array (
		'#type' => 'markup',
		'#value' => $output,
	);
	return $form;		
	

}

/**
 * Implements hook_submit() for the analisa_form() form.
 */
function analisa_form_submit($form, &$form_state) {
$uri = 'analisa/' ;

if($form_state['clicked_button']['#value'] == $form_state['values']['submit']) {
	$pdfFile = 'Analisa Belanja.pdf';
	$html = genReportBelanjaSKPDX('2');
	$header= null;
	apbd_ExportPDF3P_CF('10','10', '', $html, '', $pdfFile, '1');
	
} else	{
	genExportExcel('2');
}
}

function analisabl_form() {
	drupal_add_css('files/css/kegiatancam.css');


	$output = genReportBelanjaBySKPD('2');
	//$output = genReportBelanjaByKegiatan('2');
	/*
	$form['formdata']['submit'] = array (
		'#type' => 'submit',
		'#value' => 'Cetak'
	);	
	$form['formdata']['submitexcel'] = array (
		'#type' => 'submit',
		'#value' => 'Excel',
	);
	*/
	$form['formdata']['value'] = array (
		'#type' => 'markup',
		'#value' => $output,
	);
	
	return $form;		
	

}

/**
 * Implements hook_submit() for the analisa_form() form.
 */
function analisabl_form_submit($form, &$form_state) {
	drupal_set_message('BL');
}

function analisabtl_form() {
	drupal_add_css('files/css/kegiatancam.css');


	$output = genReportBelanjaBySKPD('1');
	/*
	$form['formdata']['submit'] = array (
		'#type' => 'submit',
		'#value' => 'Cetak'
	);
	
	$form['formdata']['submitexcel'] = array (
		'#type' => 'submit',
		'#value' => 'Excel',
	);
	*/
	$form['formdata']['value'] = array (
		'#type' => 'markup',
		'#value' => $output,
	);
	
	return $form;		
	

}


function genReportBelanjaSKPDX($jenis) {
	set_time_limit(0);
	ini_set('memory_limit', '640M');
	
	$headersrek[] = array (
						 array('data' => 'KODE',  'width'=> '60px','style' => 'border-left: 1px solid black; border-bottom: 1px solid black; border-right: 1px solid black; border-top: 1px solid black; text-align:center;'),
						 array('data' => 'URAIAN', 'width' => '350px', 'colspan'=>'5',  'style' => 'border-bottom: 1px solid black; border-right: 1px solid black; border-top: 1px solid black; text-align:center;'),
						 array('data' => '#KEG', 'width' => '30px', 'style' => 'border-bottom: 1px solid black; border-right: 1px solid black; border-top: 1px solid black; text-align:center;'),
						 array('data' => 'JUMLAH (Rp)',  'width' => '100px', 'style' => 'border-bottom: 1px solid black; border-right: 1px solid black; border-top: 1px solid black; text-align:center;'),
						 );

	$where = ' where k.kodeuk=\'%s\'';
	
	$total=0;
	 
						 
	//REKENING
	$sql = 'select k.kodero,r.uraian,sum(jumlah) jumlahx from {anggperkeg} k left join {rincianobyek} r on k.kodero=r.kodero  inner join {kegiatanskpd} keg on k.kodekeg=keg.kodekeg where keg.inaktif=0  and keg.jenis=\'%s\'';
	$fsql = sprintf($sql, $jenis);
	$fsql .= ' group by k.kodero,r.uraian order by k.kodero';
		
	
	//drupal_set_message( $fsql);
	$result= db_query($fsql);
	if ($result) {
		while ($data = db_fetch_object($result)) {
			$total += $data->jumlahx;
			//font-style: italic;
			
			$uraian = l($data->uraian, 'node/299/' . $data->kodero , array('html' =>TRUE));
			
			$rowsrek[] = array (
							 array('data' => apbd_format_rek_rincianobyek($data->kodero),  'width'=> '60px', 'style' => 'border-left: 1px solid black;  border-right: 1px solid black; text-align:left;'),
							 array('data' => $uraian, 'width' => '350px', 'colspan'=>'5',  'style' => ' border-right: 1px solid black; text-align:left;'),
							 array('data' => '', 'width' => '30px',  'style' => ' border-right: 1px solid black; text-align:left;'),
							 array('data' => apbd_fn($data->jumlahx),  'width' => '100px', 'style' => ' border-right: 1px solid black; text-align:right;'),
							 );	
							 
			//DETIL SKPD 
			$no = 0;
			$sql = 'select u.kodeuk, u.namauk,sum(k.jumlah) jumlahx from {anggperkeg} k  inner join {kegiatanskpd} keg on k.kodekeg=keg.kodekeg inner join {unitkerja} u on keg.kodeuk=u.kodeuk where keg.inaktif=0 and k.kodero=\'%s\'';
			$fsql = sprintf($sql, db_escape_string($data->kodero));
			$fsql .= ' group by u.kodeuk, u.namauk order by sum(k.jumlah) desc'; 
			//drupal_set_message($fsql);
			$resdetil= db_query($fsql);
			if ($resdetil) {
				while ($datadetil = db_fetch_object($resdetil)) {
					$no++;
					
					$numkeg = 0;
					$sql = 'select count(kodekeg) numkeg from {kegiatanskpd} where kodeuk=\'%s\' and inaktif=0 and kodekeg in (select kodekeg from {anggperkeg} where kodero=\'%s\')';
					$fsql = sprintf($sql, db_escape_string($datadetil->kodeuk), db_escape_string($data->kodero));
					$reskeg = db_query($fsql);
					if ($reskeg) {
						if ($datakeg = db_fetch_object($reskeg)) {
							$numkeg = $datakeg->numkeg;
							}
					}	
					
					$skpd = l($datadetil->namauk, 'node/299/' . $data->kodero . '/' . $datadetil->kodeuk , array('html' =>TRUE));
					
					$rowsrek[] = array (
									 array('data' => '',  'width'=> '60px', 'style' => 'border-left: 1px solid black;  border-right: 1px solid black; text-align:left;'),
									 array('data' => $no . '.',  'width'=> '50px', 'style' => 'text-align:right;'),
									 array('data' => $skpd, 'width' => '300px', 'colspan'=>'4',  'style' => ' border-right: 1px solid black; text-align:left;font-style: italic;'),
									 array('data' => $numkeg, 'width' => '30px',  'style' => ' border-right: 1px solid black; text-align:right;'),
									 array('data' => apbd_fn($datadetil->jumlahx),  'width' => '100px', 'style' => ' border-right: 1px solid black; text-align:right;font-style: italic;'),
								);												
				}	//end detil skpd		
			}
			
		}	//end rekening
		
	}												 
						

	
	$rowsrek[] = array (
						 array('data' => 'TOTAL BELANJA',  'width'=> '750px',  'colspan'=>'7',  'style' => 'border-left: 1px solid black; border-bottom: 1px solid black; border-right: 1px solid black; border-top: 1px solid black; text-align:right; font-weight:bold;'),
						 array('data' => apbd_fn($total),  'width' => '100px', 'style' => 'border-bottom: 1px solid black; border-right: 1px solid black; border-top: 1px solid black; text-align:right; font-weight:bold;'),

						 );	
						 
	

	
						 
	$opttbl = array('cellspacing'=>'1', 'cellpadding'=>'1', 'border' => '0');

	$output .= theme_box('', apbd_theme_table($headersrek, $rowsrek, $opttbl));
	
	return $output;
	
}

function genExportExcel($jenis) {
error_reporting(E_ALL);

set_time_limit(0);
ini_set('memory_limit', '640M');

ini_set('display_errors', TRUE);
ini_set('display_startup_errors', TRUE);
//date_default_timezone_set('Europe/London');

if (PHP_SAPI == 'cli')
	die('This example should only be run from a Web Browser');

/** Include PHPExcel */
require_once 'files/PHPExcel/Classes/PHPExcel.php';

// Create new PHPExcel object
$objPHPExcel = new PHPExcel();
// Set document properties
$objPHPExcel->getProperties()->setCreator("SIPKD Anggaran Online")
							 ->setLastModifiedBy("SIPKD Anggaran Online")
							 ->setTitle("Office 2007 XLSX Test Document")
							 ->setSubject("Office 2007 XLSX Test Document")
							 ->setDescription("Excel document generated from SIPKD Anggaran Online.")
							 ->setKeywords("office 2007 SIPKD Anggaran Online openxml php")
							 ->setCategory("SIPKD Anggaran Analisa");
// Add Header
$row = 1;
$objPHPExcel->setActiveSheetIndex(0)
            ->setCellValue('A' . $row ,'KODE')
			->setCellValue('B' . $row ,'URAIAN')
            ->setCellValue('C' . $row ,'KEGIATAN')
            ->setCellValue('D' . $row ,'JUMLAH');

	
$total=0;
$totalkeg=0;
						 
//REKENING
$sql = 'select k.kodero,r.uraian,sum(jumlah) jumlahx from {anggperkeg} k left join {rincianobyek} r on k.kodero=r.kodero  inner join {kegiatanskpd} keg on k.kodekeg=keg.kodekeg where keg.inaktif=0  and keg.jenis=\'%s\'';
$fsql = sprintf($sql, $jenis);
$fsql .= ' group by k.kodero,r.uraian order by k.kodero';
	

//drupal_set_message( $fsql);
$result= db_query($fsql);
if ($result) {
	while ($data = db_fetch_object($result)) {
		$total += $data->jumlahx;
		//font-style: italic;
		
		$row++;
		$objPHPExcel->setActiveSheetIndex(0)
					->setCellValue('A' . $row, apbd_format_rek_rincianobyek($data->kodero))
					->setCellValue('B' . $row, $data->uraian)
					->setCellValue('C' . $row, '')
					->setCellValue('D' . $row, $data->jumlahx);
				
						 
		//DETIL SKPD 
		$no = 0;
		$sql = 'select u.kodeuk, u.namauk,sum(k.jumlah) jumlahx from {anggperkeg} k  inner join {kegiatanskpd} keg on k.kodekeg=keg.kodekeg inner join {unitkerja} u on keg.kodeuk=u.kodeuk where keg.inaktif=0 and k.kodero=\'%s\'';
		$fsql = sprintf($sql, db_escape_string($data->kodero));
		$fsql .= ' group by u.kodeuk, u.namauk order by sum(k.jumlah) desc'; 
		//drupal_set_message($fsql);
		$resdetil= db_query($fsql);
		if ($resdetil) {
			while ($datadetil = db_fetch_object($resdetil)) {
				$no++;
				
				$numkeg = 0;
				$sql = 'select count(kodekeg) numkeg from {kegiatanskpd} where kodeuk=\'%s\' and inaktif=0 and kodekeg in (select kodekeg from {anggperkeg} where kodero=\'%s\')';
				$fsql = sprintf($sql, db_escape_string($datadetil->kodeuk), db_escape_string($data->kodero));
				$reskeg = db_query($fsql);
				if ($reskeg) {
					if ($datakeg = db_fetch_object($reskeg)) {
						$numkeg = $datakeg->numkeg;
						}
				}	
				
				$totalkeg += $numkeg;
				
				$row++;
				$objPHPExcel->setActiveSheetIndex(0)
							->setCellValue('A' . $row, '')
							->setCellValue('B' . $row, $no++ . '. ' . $datadetil->namauk)
							->setCellValue('C' . $row, $numkeg)
							->setCellValue('D' . $row, $datadetil->jumlahx);
				
										
			}	//end detil skpd		
		}
		
	}	//end rekening
	
}												 
					
$row++;
$objPHPExcel->setActiveSheetIndex(0)
			->setCellValue('A' . $row, '')
			->setCellValue('B' . $row, 'TOTAL')
			->setCellValue('C' . $row, $totalkeg)
			->setCellValue('D' . $row, $total);
						

// Rename worksheet
$objPHPExcel->getActiveSheet()->setTitle('Plafon dan Belanja SKPD');


// Set active sheet index to the first sheet, so Excel opens this as the first sheet
$objPHPExcel->setActiveSheetIndex(0);


// Redirect output to a client’s web browser (Excel2007)
header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
$fname = 'analisa_belanja.xlsx';
header('Content-Disposition: attachment;filename=' . $fname);
header('Cache-Control: max-age=0');

$objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007');
$objWriter->save('php://output');
exit;
}

function genReportBelanjaBySKPD($jenis) {
	set_time_limit(0);
	ini_set('memory_limit', '640M');
	
	$headersrek[] = array (
						 array('data' => 'KODE',  'width'=> '60px','style' => 'border-left: 1px solid black; border-bottom: 1px solid black; border-right: 1px solid black; border-top: 1px solid black; text-align:center;'),
						 array('data' => 'URAIAN', 'width' => '600px', 'colspan'=>'5',  'style' => 'border-bottom: 1px solid black; border-right: 1px solid black; border-top: 1px solid black; text-align:center;'),
						 array('data' => '# KEGIATAN', 'width' => '90px', 'style' => 'border-bottom: 1px solid black; border-right: 1px solid black; border-top: 1px solid black; text-align:center;'),
						 array('data' => 'ANGGARAN (Rp)',  'width' => '125px', 'style' => 'border-bottom: 1px solid black; border-right: 1px solid black; border-top: 1px solid black; text-align:center;'),
						 );

	
	$total=0; $totalkeg = 0;

	//JENIS
	$sql = 'select mid(k.kodero,1,3) kodej,j.uraian,sum(jumlah) jumlahx from {anggperkeg} k left join {jenis} j on mid(k.kodero,1,3)=j.kodej  inner join {kegiatanskpd} keg on k.kodekeg=keg.kodekeg where keg.inaktif=0 and keg.jenis=\'%s\'';
	$fsql = sprintf($sql, db_escape_string($jenis));
	$fsql .= ' group by mid(k.kodero,1,3),j.uraian order by mid(k.kodero,1,3)';				

	//drupal_set_message( $fsql);
	$resultjenis = db_query($fsql);
	if ($resultjenis) {
		while ($datajenis = db_fetch_object($resultjenis)) {

			$total += $datajenis->jumlahx;
		
			$rowsrek[] = array (
							 array('data' => ($datajenis->kodej),  'width'=> '60px', 'style' => 'border-left: 1px solid black;  border-right: 1px solid black; text-align:left;'),
							 array('data' => $datajenis->uraian, 'width' => '600px', 'colspan'=>'5',  'style' => ' border-right: 1px solid black; text-align:left;font-weight:bold;'),
							 array('data' => '', 'width' => '90px',  'style' => ' border-right: 1px solid black; text-align:left;'),
							 array('data' => apbd_fn($datajenis->jumlahx),  'width' => '125px', 'style' => ' border-right: 1px solid black; border-bottom: 2px solid black; text-align:right;font-weight:bold;'),

							 );

			//OBYEK
			$sql = 'select mid(k.kodero,1,5) kodeo,j.uraian,sum(jumlah) jumlahx from {anggperkeg} k left join {obyek} j on mid(k.kodero,1,5)=j.kodeo  inner join {kegiatanskpd} keg on k.kodekeg=keg.kodekeg where keg.inaktif=0 and mid(k.kodero,1,3)=\'%s\'';
			$fsql = sprintf($sql, db_escape_string($datajenis->kodej));
			$fsql .= ' group by mid(k.kodero,1,5),j.uraian order by j.kodeo';
		
			$resultobyek = db_query($fsql);
			if ($resultobyek) {
				while ($dataobyek = db_fetch_object($resultobyek)) {
					
					
					$rowsrek[] = array (
								 array('data' => apbd_format_rek_obyek($dataobyek->kodeo),  'width'=> '60px', 'style' => 'border-left: 1px solid black;  border-right: 1px solid black; text-align:left;'),
								 array('data' => $dataobyek->uraian, 'width' => '600px', 'colspan'=>'5',  'style' => ' border-right: 1px solid black; text-align:left;font-weight:bold;'),
								 array('data' => '', 'width' => '90px',  'style' => ' border-right: 1px solid black; text-align:left;'),
								 array('data' => apbd_fn($dataobyek->jumlahx),  'width' => '125px', 'style' => ' border-right: 1px solid black; text-align:right;font-weight:bold;'),
								 );		 
										 
					//REKENING
					$sql = 'select k.kodero,r.uraian,sum(jumlah) jumlahx from {anggperkeg} k left join {rincianobyek} r on k.kodero=r.kodero  inner join {kegiatanskpd} keg on k.kodekeg=keg.kodekeg where keg.inaktif=0 and  left(k.kodero,5)=\'%s\'';
					$fsql = sprintf($sql, db_escape_string($dataobyek->kodeo));
					$fsql .= ' group by k.kodero,r.uraian order by k.kodero';
						
					
					//drupal_set_message( $fsql);
					$result= db_query($fsql);
					if ($result) {
						while ($data = db_fetch_object($result)) {

							//font-style: italic;
							$rowsrek[] = array (
											 array('data' => apbd_format_rek_rincianobyek($data->kodero),  'width'=> '60px', 'style' => 'border-left: 1px solid black;  border-right: 1px solid black; text-align:left;'),
											 array('data' => $data->uraian, 'width' => '600px', 'colspan'=>'5',  'style' => ' border-right: 1px solid black; text-align:left;'),
											 array('data' => '', 'width' => '90px',  'style' => ' border-right: 1px solid black; text-align:left;'),
											 array('data' => apbd_fn($data->jumlahx),  'width' => '125px', 'style' => ' border-right: 1px solid black; text-align:right;'),
											 );	
											 
							//DETIL SKPD 
							$no = 0;
							$sql = 'select u.kodeuk, u.namauk,sum(k.jumlah) jumlahx from {anggperkeg} k  inner join {kegiatanskpd} keg on k.kodekeg=keg.kodekeg inner join {unitkerja} u on keg.kodeuk=u.kodeuk where keg.inaktif=0 and k.kodero=\'%s\'';
							$fsql = sprintf($sql, db_escape_string($data->kodero));
							$fsql .= ' group by u.kodeuk, u.namauk order by sum(k.jumlah) desc'; 
							//drupal_set_message($fsql);
							$resdetil= db_query($fsql);
							if ($resdetil) {
								while ($datadetil = db_fetch_object($resdetil)) {
									$no++;
									
									$numkeg = 0;
									$sql = 'select count(kodekeg) numkeg from {kegiatanskpd} where kodeuk=\'%s\' and inaktif=0 and kodekeg in (select kodekeg from {anggperkeg} where kodero=\'%s\')';
									$fsql = sprintf($sql, db_escape_string($datadetil->kodeuk), db_escape_string($data->kodero));
									$reskeg = db_query($fsql);
									if ($reskeg) {
										if ($datakeg = db_fetch_object($reskeg)) {
											$numkeg = $datakeg->numkeg;
											}
									}	
									
									$totalkeg += $numkeg;

									$skpd = l($datadetil->namauk, 'node/299/' . $data->kodero . '/' . $datadetil->kodeuk , array('html' =>TRUE));
								
									
									$rowsrek[] = array (
													 array('data' => '',  'width'=> '60px', 'style' => 'border-left: 1px solid black;  border-right: 1px solid black; text-align:left;'),
													 array('data' => $no . '.',  'width'=> '50px', 'style' => 'text-align:right;'),
													 array('data' => $skpd, 'width' => '550px', 'colspan'=>'4',  'style' => ' border-right: 1px solid black; text-align:left;font-style: italic;'),
													 array('data' => $numkeg, 'width' => '90px',  'style' => ' border-right: 1px solid black; text-align:right;'),
													 array('data' => apbd_fn($datadetil->jumlahx),  'width' => '125px', 'style' => ' border-right: 1px solid black; text-align:right;font-style: italic;'),
												);												
								}	//end detil skpd		
							}
							
						}	//end rekening
						
					}												 
				
				}	//end obyek
			}
		}
	}										 
						 


	$rowsrek[] = array (
						 array('data' => 'TOTAL BELANJA',  'width'=> '750px',  'colspan'=>'6',  'style' => 'border-left: 1px solid black; border-bottom: 1px solid black; border-right: 1px solid black; border-top: 1px solid black; text-align:right; font-weight:bold;'),
						 array('data' => apbd_fn($totalkeg),  'width' => '125px', 'style' => 'border-bottom: 1px solid black; border-right: 1px solid black; border-top: 1px solid black; text-align:right; font-weight:bold;'),
						 array('data' => apbd_fn($total),  'width' => '125px', 'style' => 'border-bottom: 1px solid black; border-right: 1px solid black; border-top: 1px solid black; text-align:right; font-weight:bold;'),

						 );	
						 
	

	
						 
	$opttbl = array('cellspacing'=>'1', 'cellpadding'=>'1', 'border' => '0');

	$output .= theme_box('', apbd_theme_table($headersrek, $rowsrek, $opttbl));
	
	return $output;
	
}

function genReportBelanjaByKegiatan($jenis) {
	set_time_limit(0);
	ini_set('memory_limit', '640M');
	
	$headersrek[] = array (
						 array('data' => 'KODE',  'width'=> '60px','style' => 'border-left: 1px solid black; border-bottom: 1px solid black; border-right: 1px solid black; border-top: 1px solid black; text-align:center;'),
						 array('data' => 'URAIAN', 'width' => '600px', 'colspan'=>'5',  'style' => 'border-bottom: 1px solid black; border-right: 1px solid black; border-top: 1px solid black; text-align:center;'),
						 array('data' => 'ANGGARAN (Rp)',  'width' => '125px', 'style' => 'border-bottom: 1px solid black; border-right: 1px solid black; border-top: 1px solid black; text-align:center;'),
						 );

	
	$total=0; $totalkeg = 0;

	//JENIS
	$sql = 'select mid(k.kodero,1,3) kodej,j.uraian,sum(jumlah) jumlahx from {anggperkeg} k left join {jenis} j on mid(k.kodero,1,3)=j.kodej  inner join {kegiatanskpd} keg on k.kodekeg=keg.kodekeg where keg.inaktif=0 and keg.jenis=\'%s\'';
	$fsql = sprintf($sql, db_escape_string($jenis));
	$fsql .= ' group by mid(k.kodero,1,3),j.uraian order by mid(k.kodero,1,3)';				

	//drupal_set_message( $fsql);
	$resultjenis = db_query($fsql);
	if ($resultjenis) {
		while ($datajenis = db_fetch_object($resultjenis)) {

			$total += $datajenis->jumlahx;
		
			$rowsrek[] = array (
							 array('data' => ($datajenis->kodej),  'width'=> '60px', 'style' => 'border-left: 1px solid black;  border-right: 1px solid black; text-align:left;'),
							 array('data' => $datajenis->uraian, 'width' => '600px', 'colspan'=>'5',  'style' => ' border-right: 1px solid black; text-align:left;font-weight:bold;'),
							 array('data' => apbd_fn($datajenis->jumlahx),  'width' => '125px', 'style' => ' border-right: 1px solid black; border-bottom: 2px solid black; text-align:right;font-weight:bold;'),

							 );

			//OBYEK
			$sql = 'select mid(k.kodero,1,5) kodeo,j.uraian,sum(jumlah) jumlahx from {anggperkeg} k left join {obyek} j on mid(k.kodero,1,5)=j.kodeo  inner join {kegiatanskpd} keg on k.kodekeg=keg.kodekeg where keg.inaktif=0 and mid(k.kodero,1,3)=\'%s\'';
			$fsql = sprintf($sql, db_escape_string($datajenis->kodej));
			$fsql .= ' group by mid(k.kodero,1,5),j.uraian order by j.kodeo';
		
			$resultobyek = db_query($fsql);
			if ($resultobyek) {
				while ($dataobyek = db_fetch_object($resultobyek)) {
					
					
					$rowsrek[] = array (
								 array('data' => apbd_format_rek_obyek($dataobyek->kodeo),  'width'=> '60px', 'style' => 'border-left: 1px solid black;  border-right: 1px solid black; text-align:left;'),
								 array('data' => $dataobyek->uraian, 'width' => '600px', 'colspan'=>'5',  'style' => ' border-right: 1px solid black; text-align:left;font-weight:bold;'),
								 array('data' => apbd_fn($dataobyek->jumlahx),  'width' => '125px', 'style' => ' border-right: 1px solid black; text-align:right;font-weight:bold;'),
								 );		 
										 
					//REKENING
					$sql = 'select k.kodero,r.uraian,sum(jumlah) jumlahx from {anggperkeg} k left join {rincianobyek} r on k.kodero=r.kodero  inner join {kegiatanskpd} keg on k.kodekeg=keg.kodekeg where keg.inaktif=0 and  left(k.kodero,5)=\'%s\'';
					$fsql = sprintf($sql, db_escape_string($dataobyek->kodeo));
					$fsql .= ' group by k.kodero,r.uraian order by k.kodero';
						
					
					//drupal_set_message( $fsql);
					$result= db_query($fsql);
					if ($result) {
						while ($data = db_fetch_object($result)) {

							//font-style: italic;
							$rowsrek[] = array (
											 array('data' => apbd_format_rek_rincianobyek($data->kodero),  'width'=> '60px', 'style' => 'border-left: 1px solid black;  border-right: 1px solid black; text-align:left;'),
											 array('data' => $data->uraian, 'width' => '600px', 'colspan'=>'5',  'style' => ' border-right: 1px solid black; text-align:left;'),
											 array('data' => '', 'width' => '90px',  'style' => ' border-right: 1px solid black; text-align:left;'),
											 array('data' => apbd_fn($data->jumlahx),  'width' => '125px', 'style' => ' border-right: 1px solid black; text-align:right;'),
											 );	
											 
							//DETIL SKPD 
							$no = 0;
							$sql = 'select u.kodeuk, u.namauk,sum(k.jumlah) jumlahx from {anggperkeg} k  inner join {kegiatanskpd} keg on k.kodekeg=keg.kodekeg inner join {unitkerja} u on keg.kodeuk=u.kodeuk where keg.inaktif=0 and k.kodero=\'%s\'';
							$fsql = sprintf($sql, db_escape_string($data->kodero));
							$fsql .= ' group by u.kodeuk, u.namauk order by sum(k.jumlah) desc'; 
							//drupal_set_message($fsql);
							$resdetil= db_query($fsql);
							if ($resdetil) {
								while ($datadetil = db_fetch_object($resdetil)) {
									$no++;
									

									$rowsrek[] = array (
													 array('data' => '',  'width'=> '60px', 'style' => 'border-left: 1px solid black;  border-right: 1px solid black; text-align:left;'),
													 array('data' => $no . '.',  'width'=> '50px', 'style' => 'text-align:right;'),
													 array('data' => $datadetil->namauk, 'width' => '550px', 'colspan'=>'4',  'style' => ' border-right: 1px solid black; text-align:left;font-style: italic;'),
													 array('data' => $numkeg, 'width' => '90px',  'style' => ' border-right: 1px solid black; text-align:right;'),
													 array('data' => apbd_fn($datadetil->jumlahx),  'width' => '125px', 'style' => ' border-right: 1px solid black; text-align:right;font-style: italic;'),
												);		

									//KEGIATAN
									$nokeg = 0;
									$sql = 'select keg.kodekeg, keg.kegiatan, k.jumlah from {anggperkeg} k inner join {kegiatanskpd} keg on k.kodekeg=keg.kodekeg where keg.inaktif=0 and k.kodero=\'%s\' and keg.kodeuk=\'%s\'';
									$fsql = sprintf($sql, $data->kodero, $datadetil->kodeuk);
									$fsql .= ' order by k.jumlah desc';
									
									//drupal_set_message($fsql);
									
									$reskeg= db_query($fsql);
									
									while ($datakeg = db_fetch_object($reskeg)) {
										$nokeg;
										$rowsrek[] = array (
														 array('data' => '',  'width'=> '60px', 'style' => 'border-left: 1px solid black;  border-right: 1px solid black; text-align:left;'),
														 array('data' => '',  'width'=> '50px', 'style' => 'text-align:right;'),
														 array('data' => '-',  'width'=> '50px', 'style' => 'text-align:center;'),
														 array('data' => $datakeg->kegiatan, 'width' => '500px', 'colspan'=>'3',  'style' => ' border-right: 1px solid black; text-align:left;font-style: italic;'),
														 array('data' => apbd_fn($datakeg->jumlah),  'width' => '125px', 'style' => ' border-right: 1px solid black; text-align:right;font-style: italic;'),
													);										
									}
								}	//end detil skpd		
							}
							
						}	//end rekening
						
					}												 
				
				}	//end obyek
			}
		}
	}										 
						 


	$rowsrek[] = array (
						 array('data' => 'TOTAL BELANJA',  'width'=> '750px',  'colspan'=>'6',  'style' => 'border-left: 1px solid black; border-bottom: 1px solid black; border-right: 1px solid black; border-top: 1px solid black; text-align:right; font-weight:bold;'),
						 array('data' => apbd_fn($totalkeg),  'width' => '125px', 'style' => 'border-bottom: 1px solid black; border-right: 1px solid black; border-top: 1px solid black; text-align:right; font-weight:bold;'),
						 array('data' => apbd_fn($total),  'width' => '125px', 'style' => 'border-bottom: 1px solid black; border-right: 1px solid black; border-top: 1px solid black; text-align:right; font-weight:bold;'),

						 );	
						 
	

	
						 
	$opttbl = array('cellspacing'=>'1', 'cellpadding'=>'1', 'border' => '0');

	$output .= theme_box('', apbd_theme_table($headersrek, $rowsrek, $opttbl));
	
	return $output;
	
}


